version: '3'
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    command: npm start
